import { useState, type FormEvent } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { toast } from "sonner";
import { AdminShell } from "@/components/admin/AdminShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_admin/admin/change-password")({head:()=>({meta:[{title:"Change Temporary Password — GIMATech"},{name:"description",content:"Secure GIMATech administrator password update."},{property:"og:title",content:"Change Temporary Password — GIMATech"},{property:"og:description",content:"Secure administrator password update."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:ChangePassword});
function ChangePassword(){const navigate=useNavigate();const[p,setP]=useState("");const[c,setC]=useState("");const[e,setE]=useState("");const[busy,setBusy]=useState(false);const submit=async(ev:FormEvent)=>{ev.preventDefault();setE("");if(p.length<10)return setE("Use at least 10 characters for your new password.");if(p!==c)return setE("The passwords do not match.");setBusy(true);const{error}=await supabase.auth.updateUser({password:p});if(error){setE("Your password could not be changed. Please try again.");setBusy(false);return;}const{error:updateError}=await supabase.from("admin_accounts").update({must_change_password:false}).eq("user_id",(await supabase.auth.getUser()).data.user?.id??"");if(updateError){setE("Your password changed, but setup could not be completed. Please contact the Super Admin.");setBusy(false);return;}toast.success("Password changed securely");navigate({to:"/admin/dashboard",replace:true});};return <AdminShell><div className="mx-auto max-w-xl p-4 py-12 sm:p-8"><form onSubmit={submit} className="rounded-lg border border-primary/30 bg-card p-6 shadow-card sm:p-8"><p className="eyebrow">Required security step</p><h1 className="mt-2 text-3xl font-bold">Change your temporary password</h1><p className="mt-3 text-sm text-muted-foreground">Please change your temporary password before continuing.</p><div className="mt-7 space-y-2"><Label htmlFor="new-password">New password</Label><Input id="new-password" type="password" value={p} onChange={x=>setP(x.target.value)} autoComplete="new-password"/></div><div className="mt-5 space-y-2"><Label htmlFor="confirm-password">Confirm new password</Label><Input id="confirm-password" type="password" value={c} onChange={x=>setC(x.target.value)} autoComplete="new-password"/></div>{e&&<p className="mt-4 text-sm text-destructive">{e}</p>}<Button className="mt-6 w-full" size="lg" disabled={busy}>{busy?"Updating…":"Change Password"}</Button></form></div></AdminShell>}