import { createFileRoute, Link } from "@tanstack/react-router";
import { Heart, LogOut, MapPin, Package, Settings, UserRound } from "lucide-react";
import { z } from "zod";
import { StorePage } from "@/components/layout/StorePage";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/context/AuthContext";
const schema=z.object({section:z.enum(["orders","addresses","settings"]).optional()});
export const Route=createFileRoute("/account")({validateSearch:schema,head:()=>({meta:[{title:"My Account — GIMATech"},{name:"description",content:"Manage your GIMATech customer profile, wishlist and account settings."},{property:"og:title",content:"My Account — GIMATech"},{property:"og:description",content:"Your private GIMATech customer account."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:AccountPage});
function AccountPage(){const{user,profile,loading,signOut}=useAuth();const{section}=Route.useSearch();if(loading)return <StorePage><div className="section-shell py-24 text-center text-muted-foreground">Loading your account…</div></StorePage>;if(!user)return <StorePage><div className="section-shell py-24 text-center"><h1 className="text-3xl font-bold">Sign in to your account</h1><p className="mt-3 text-muted-foreground">Your account details and saved items are private.</p><Button asChild className="mt-6"><Link to="/login" search={{redirect:"/account"}}>Login</Link></Button></div></StorePage>;const title=section==="orders"?"My Orders":section==="addresses"?"Saved Addresses":section==="settings"?"Account Settings":"My Account";return <StorePage><div className="section-shell py-12 sm:py-16"><div className="grid gap-8 lg:grid-cols-[240px_1fr]"><aside className="h-fit rounded-lg border border-border bg-card p-3"><AccountLink icon={UserRound} label="My Account"/><AccountLink icon={Package} label="My Orders" section="orders"/><AccountLink icon={Heart} label="Wishlist" to="/wishlist"/><AccountLink icon={MapPin} label="Addresses" section="addresses"/><AccountLink icon={Settings} label="Settings" section="settings"/><Button variant="ghost" className="mt-2 w-full justify-start text-destructive" onClick={signOut}><LogOut/>Logout</Button></aside><section><p className="eyebrow">Customer area</p><h1 className="mt-2 text-4xl font-bold">{title}</h1>{!section?<div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-lg border border-border bg-card p-6"><p className="text-xs font-bold uppercase text-primary">Profile</p><h2 className="mt-3 text-xl font-bold">{profile?.full_name??"GIMATech customer"}</h2><p className="mt-2 text-sm text-muted-foreground">@{profile?.username??"customer"}</p><p className="mt-1 text-sm text-muted-foreground">{profile?.contact??user.phone}</p></div><div className="rounded-lg border border-border bg-card p-6"><p className="text-xs font-bold uppercase text-primary">Account status</p><h2 className="mt-3 text-xl font-bold">Securely signed in</h2><p className="mt-2 text-sm text-muted-foreground">Your account is managed by GIMATech's secure customer authentication service.</p></div></div>:<div className="mt-7 rounded-lg border border-border bg-card p-8"><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">This area is ready for connection to the future order and customer service system. No sample customer data is shown.</p>{section==="orders"&&<Button asChild className="mt-5"><Link to="/shop">Continue Shopping</Link></Button>}</div>}</section></div></div></StorePage>}
function AccountLink({icon:Icon,label,section,to}:{icon:typeof UserRound;label:string;section?:"orders"|"addresses"|"settings";to?:"/wishlist"}){return <Button asChild variant="ghost" className="w-full justify-start"><Link to={to??"/account"} search={to?undefined:{section}}><Icon/>{label}</Link></Button>}