import { useState, type FormEvent } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { LogIn } from "lucide-react";
import { z } from "zod";
import { StorePage } from "@/components/layout/StorePage";
import { PasswordInput } from "@/components/auth/PasswordInput";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { authErrorMessage, normalizePhone } from "@/lib/validation";
import { useAuth } from "@/context/AuthContext";

const loginSearch=z.object({redirect:z.string().optional()});
export const Route=createFileRoute("/login")({validateSearch:loginSearch,head:()=>({meta:[{title:"Login — GIMATech"},{name:"description",content:"Sign in securely to your GIMATech customer account."},{property:"og:title",content:"Login — GIMATech"},{property:"og:description",content:"Access your GIMATech customer account."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:LoginPage});
function LoginPage(){const navigate=useNavigate({from:"/login"});const search=Route.useSearch();const{user}=useAuth();const[values,setValues]=useState({username:"",contact:"",password:""});const[errors,setErrors]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);if(user)return <StorePage><div className="section-shell py-24 text-center"><h1 className="text-3xl font-bold">You’re already signed in</h1><Button asChild className="mt-6"><Link to="/account">Open My Account</Link></Button></div></StorePage>;async function submit(e:FormEvent){e.preventDefault();const next:Record<string,string>={};if(!values.username.trim())next.username="Please enter your username.";if(!normalizePhone(values.contact))next.contact="Please enter a valid contact number.";if(!values.password)next.password="Please enter your password.";setErrors(next);if(Object.keys(next).length)return;setBusy(true);const phone=normalizePhone(values.contact);if(!phone){setBusy(false);return;}const{error}=await supabase.auth.signInWithPassword({phone,password:values.password});if(error){setErrors({form:authErrorMessage(error.message)});setBusy(false);return;}const destination=search.redirect?.startsWith("/")?search.redirect:"/account";navigate({to:destination});}return <AuthShell title="Welcome back to GIMATech" subtitle="Sign in with your username, contact number and password."><form onSubmit={submit} className="space-y-4" noValidate><Field label="Username" error={errors.username}><Input value={values.username} onChange={(e)=>setValues({...values,username:e.target.value})} placeholder="Enter your username" className="h-11 bg-surface" autoComplete="username"/></Field><Field label="Contact" error={errors.contact}><Input value={values.contact} onChange={(e)=>setValues({...values,contact:e.target.value})} placeholder="Enter your contact number" className="h-11 bg-surface" inputMode="tel" autoComplete="tel"/></Field><Field label="Password" error={errors.password}><PasswordInput value={values.password} onChange={(e)=>setValues({...values,password:e.target.value})} placeholder="Enter your password" autoComplete="current-password"/></Field>{errors.form&&<p role="alert" className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{errors.form}</p>}<Button type="submit" size="lg" className="w-full" disabled={busy}><LogIn/>{busy?"Signing in…":"Login"}</Button><p className="text-center text-sm text-muted-foreground">Don't have an account? <Link to="/register" className="font-bold text-primary hover:underline">Create Account</Link></p></form></AuthShell>}
export function AuthShell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <StorePage><section className="section-shell grid min-h-[70vh] place-items-center py-12"><div className="w-full max-w-md rounded-lg border border-border bg-card p-6 shadow-card sm:p-8"><p className="eyebrow">Customer account</p><h1 className="mt-2 text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{subtitle}</p><div className="mt-7">{children}</div></div></section></StorePage>}
export function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <div><Label>{label}</Label><div className="mt-2">{children}</div>{error&&<p role="alert" className="mt-1.5 text-xs font-semibold text-destructive">{error}</p>}</div>}