import { useMemo } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Search, SlidersHorizontal } from "lucide-react";
import { z } from "zod";
import { StorePage } from "@/components/layout/StorePage";
import { ProductCard } from "@/components/products/ProductCard";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { products, categories } from "@/data/catalog";

const searchSchema = z.object({ q: z.string().optional(), category: z.string().optional(), brand: z.string().optional(), availability: z.string().optional(), rating: z.coerce.number().optional(), maxPrice: z.coerce.number().optional(), type: z.string().optional(), sort: z.string().optional(), deals: z.coerce.boolean().optional() });
export const Route = createFileRoute("/shop")({ validateSearch: searchSchema, head: () => ({ meta: [{ title: "Shop Technology — GIMATech Ghana" }, { name: "description", content: "Browse demo laptops, networking, storage, audio and accessories from GIMATech." }, { property: "og:title", content: "Shop Technology — GIMATech Ghana" }, { property: "og:description", content: "Explore the GIMATech technology catalogue with search, categories and useful filters." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ShopPage });

function ShopPage() {
  const search = Route.useSearch(); const navigate = useNavigate({ from: "/shop" });
  const brands = [...new Set(products.map((product) => product.brand))];
  const update = (next: Partial<typeof search>) => navigate({ search: (prev) => ({ ...prev, ...next }) });
  const filtered = useMemo(() => {
    const q = search.q?.trim().toLowerCase();
    const list = products.filter((p) => (!q || `${p.name} ${p.brand} ${p.category} ${p.description} ${(p.keywords ?? []).join(" ")}`.toLowerCase().includes(q)) && (!search.category || search.category === "all" || p.category === search.category) && (!search.brand || search.brand === "all" || p.brand === search.brand) && (!search.maxPrice || p.price <= search.maxPrice) && (!search.rating || p.rating >= search.rating) && (!search.deals || Boolean(p.previousPrice)));
    return [...list].sort((a,b) => search.sort === "price-low" ? a.price-b.price : search.sort === "price-high" ? b.price-a.price : search.sort === "rating" ? b.rating-a.rating : Number(Boolean(b.featured))-Number(Boolean(a.featured)));
  }, [search]);
  return <StorePage><section className="border-b border-border bg-surface"><div className="section-shell py-12 sm:py-16"><p className="eyebrow">Technology catalogue</p><h1 className="mt-2 font-display text-4xl font-bold text-foreground sm:text-5xl">{search.deals ? "Current Deals" : "Shop GIMATech"}</h1><p className="mt-3 text-silver-muted">{search.deals ? "Only demo products with an active promotional price are shown." : "Search and compare our development catalogue of technology products."}</p></div></section><section className="section-shell py-10"><div className="flex flex-col gap-4 rounded-lg border border-border bg-card p-4 lg:flex-row lg:items-end"><label className="relative flex-1 text-xs font-bold text-silver">Search<Search className="absolute bottom-3 left-3 size-4 text-muted-foreground" /><Input value={search.q ?? ""} onChange={(e) => update({ q: e.target.value || undefined })} placeholder="Search products, brands, categories..." className="mt-2 h-11 bg-surface pl-9" /></label><Filter label="Category" value={search.category ?? "all"} onChange={(value) => update({ category: value === "all" ? undefined : value })} options={["all", ...categories.map((c) => c.name)]} /><Filter label="Brand" value={search.brand ?? "all"} onChange={(value) => update({ brand: value === "all" ? undefined : value })} options={["all", ...brands]} /><Filter label="Sort" value={search.sort ?? "featured"} onChange={(sort) => update({ sort })} options={["featured","price-low","price-high","rating"]} labels={{ "price-low":"Price: Low to high", "price-high":"Price: High to low", rating:"Highest rated" }} /></div><div className="mt-7 flex items-center justify-between"><p className="text-sm text-muted-foreground"><strong className="text-foreground">{filtered.length}</strong> products found</p><span className="flex items-center gap-2 text-xs text-muted-foreground"><SlidersHorizontal className="size-4 text-primary" /> Filters update instantly</span></div>{filtered.length ? <div className="mt-5 grid grid-cols-1 gap-4 min-[480px]:grid-cols-2 lg:grid-cols-4">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="my-16 rounded-lg border border-dashed border-border bg-card p-10 text-center"><h2 className="text-xl font-bold">No products found</h2><p className="mt-2 text-sm text-muted-foreground">Try another search or clear a category filter.</p><button className="mt-5 text-sm font-bold text-primary" onClick={() => navigate({ search: {} })}>Return to all products</button></div>}</section></StorePage>;
}
function Filter({ label, value, onChange, options, labels = {} }: { label: string; value: string; onChange: (value: string) => void; options: string[]; labels?: Record<string,string> }) { return <label className="min-w-44 text-xs font-bold text-silver">{label}<Select value={value} onValueChange={onChange}><SelectTrigger className="mt-2 h-11 bg-surface"><SelectValue /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option} value={option}>{labels[option] ?? (option === "all" ? `All ${label.toLowerCase()}s` : option === "featured" ? "Featured" : option)}</SelectItem>)}</SelectContent></Select></label>; }