import { useState, type FormEvent } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Eye, EyeOff, LockKeyhole } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { resolveAdminLogin } from "@/lib/admin.functions";
import logoAsset from "@/assets/gimatech-official-logo.png.asset.json";

export const Route = createFileRoute("/admin/login")({ head: () => ({ meta: [{ title: "Administrator Login — GIMATech" }, { name: "description", content: "Secure GIMATech administrator access." }, { property: "og:title", content: "Administrator Login — GIMATech" }, { property: "og:description", content: "Secure GIMATech administrator access." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AdminLogin });
function AdminLogin() { const resolve = useServerFn(resolveAdminLogin); const navigate = useNavigate(); const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(!username.trim())return setError("Please enter your username.");if(!password)return setError("Please enter your password.");setBusy(true);try{const tokens=await resolve({data:{username,password}});const {error:authError}=await supabase.auth.setSession({access_token:tokens.accessToken,refresh_token:tokens.refreshToken});if(authError)throw authError;navigate({to:"/admin/dashboard",replace:true});}catch{setError("Invalid username or password.");}finally{setBusy(false)}};
  return <main className="grid min-h-screen bg-background lg:grid-cols-[1.05fr_.95fr]"><section className="hidden border-r border-border bg-charcoal p-12 lg:flex lg:flex-col lg:justify-between"><img src={logoAsset.url} className="h-16 w-48 object-contain object-left" alt="GIMA Technologies"/><div><p className="eyebrow">Protected operations</p><h1 className="mt-4 max-w-lg text-5xl font-extrabold leading-tight">Technology management, securely controlled.</h1><p className="mt-5 max-w-md text-silver-muted">Role-based access for authorised GIMATech administrators.</p></div><p className="text-xs text-muted-foreground">Administrative activity is monitored and recorded.</p></section><section className="flex items-center justify-center px-4 py-12"><form onSubmit={submit} className="w-full max-w-md rounded-lg border border-border bg-card p-6 shadow-card sm:p-8"><div className="mb-7 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-md bg-primary-soft text-primary"><LockKeyhole/></span><div><h2 className="text-2xl font-bold">Admin Login</h2><p className="text-sm text-muted-foreground">Enter your authorised credentials.</p></div></div><div className="space-y-2"><Label htmlFor="username">Username</Label><Input id="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter your username" autoComplete="username"/></div><div className="mt-5 space-y-2"><Label htmlFor="password">Password</Label><div className="relative"><Input id="password" type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password" className="pr-11"/><Button type="button" variant="ghost" size="icon" className="absolute right-1 top-0" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff/>:<Eye/>}</Button></div></div>{error&&<p className="mt-4 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<Button className="mt-6 w-full" size="lg" disabled={busy}>{busy?"Verifying…":"Login"}</Button><Button asChild variant="link" className="mt-3 w-full"><Link to="/">Return to store</Link></Button></form></section></main>;
}